---
- name: Configurare Podman su tutti i nodi
  hosts: all
  remote_user: vagrant
  become: true
  roles:
    - sou_podman

- name: Configurare HAProxy solo su soufe1
  hosts: soufe1
  remote_user: vagrant
  become: true
  roles:
    - sou_haproxy
  handlers:
  - name: Riavviare HAProxy
    containers.podman.podman_container:
      name: haproxy
      state: started

- name: Installare e configurare monitoring su soube2
  hosts: soube2
  remote_user: vagrant
  become: true
  roles:
    - sou_monitoring